### ISSUE TITLE
Contribution Status of members is wanting.

### ISSUE THREAD

**Issue by BrianLusina** [Harrisonkamau/python-peers#4]
I see no contribution to this repo. Very few of the problems I have pushed have been solved.
Point of this repo again?
Kindly contribute to this repo.

**Comment by valdadyne** [comment]
Agreed.

**Comment by Harrisonkamau** [comment]
Any contributor not continuing with Python?

**Comment by BrianLusina** [comment]
I think everyone here is doing Python.

**Comment by Harrisonkamau** [comment]
How many contributors have been sharing questions?

**Comment by BrianLusina** [comment]
Umm, as far as the :bar_chart: shows, I have been the only one pushing the questions. I encourage others to do the same.

**Comment by Harrisonkamau** [comment]
Keep up the good work, as we encourage the other members to chip in.
Hope hujacatch:-)

**Comment by BrianLusina** [comment]
Hehe, :laughing: sijacatch. Quite concerned about the contribution levels. Wanted to notify people on it.

**Comment by Harrisonkamau** [comment]
Your cry has been heard,
Be well my friend:)

**Comment by BrianLusina** [comment]
Thank you Deputy (I sweat this is the last time I call you this :smile:)
Be well.

**Comment by Harrisonkamau** [comment]
I am the principal!
