### ISSUE TITLE
Allergies.py problem 

### ISSUE THREAD

**Issue by johnngugi** [Harrisonkamau/python-peers#5]
If you look at the 4 bottom tests in the file, the **lst** method isn't being called properly  
Eg: self.assertEqual(['peanuts'], Allergies(2).lst)
The above would give you an error even when the correct answer is given but :    self.assertEqual(['peanuts'], Allergies(2).lst())
would pass

Is the second way the correct way or the first one??

**Comment by BrianLusina** [comment]
The `Allergies(2).lst` is not calling a function, but rather a list. So using `Allergies(2).lst()` would signify calling a function inside the `Allergies` class. 
Remember to program should be able to do two things :point_right: `...can tell them whether or not they're allergic to a given item, and their full list of allergies`
You could initialize `self.lst` such that it is a variable and not a method an example(hint):

``` python
  def __init__(self, score):
       ...other variables
       self.lst = list("""create your list here from your is_allergic_to method""")

```
